apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../apps/namespace.yaml

  # Redis
  - ../../apps/redis/deployment.yaml
  - ../../apps/redis/service.yaml

  # Ollama
  - ../../apps/ollama/pvc.yaml
  - ../../apps/ollama/deployment.yaml
  - ../../apps/ollama/service.yaml
  - ../../apps/ollama/models.yaml

  # OpenWebUI
  - ../../apps/openwebui/pvc.yaml
  - ../../apps/openwebui/deployment.yaml
  - ../../apps/openwebui/service.yaml
