apiVersion: batch/v1
kind: Job

metadata:
  name: pull-models
  namespace: ollama

spec:
  backoffLimit: 3

  template:
    spec:
      restartPolicy: Never

      containers:
      - name: pull-models

        image: ollama/ollama:latest

        command:
        - /bin/sh
        - -c
        - |
          sleep 60

          export OLLAMA_HOST=http://ollama:11434

          ollama list | grep mistral

          if [ $? -ne 0 ]; then
            ollama pull mistral
          fi

          ollama list | grep qwen3:8b

          if [ $? -ne 0 ]; then
            ollama pull qwen3:8b
          fi

          ollama list | grep llama3.1:8b

          if [ $? -ne 0 ]; then
            ollama pull llama3.1:8b
          fi
